### ISSUE TITLE
PHP Fatal error:  Class 'Lstr\DnsmasqMgmt\Service\Exception' not found in /root/.composer/vendor/lightster/dnsmasq-mgmt/src/Lstr/DnsmasqMgmt/Service/DnsmasqMgmtServiceProvider.php on line 28

### ISSUE THREAD

**Issue by gpetrache-at-ca** [lightster/dnsmasq-mgmt#16]
OS: Fedora release 20 (Heisenbug)

[gpetrache@powerbox ~]$ sudo /root/.composer/vendor/bin/dnsmasq-mgmt sudoers:install
PHP Fatal error:  Class 'Lstr\DnsmasqMgmt\Service\Exception' not found in /root/.composer/vendor/lightster/dnsmasq-mgmt/src/Lstr/DnsmasqMgmt/Service/DnsmasqMgmtServiceProvider.php on line 28
PHP Stack trace:
PHP   1. {main}() /root/.composer/vendor/lightster/dnsmasq-mgmt/bin/dnsmasq-mgmt:0
PHP   2. Symfony\Component\Console\Application->run() /root/.composer/vendor/lightster/dnsmasq-mgmt/bin/dnsmasq-mgmt:45
PHP   3. Symfony\Component\Console\Application->doRun() /root/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /root/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /root/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   6. Lstr\DnsmasqMgmt\Command\SudoersSetupCommand->execute() /root/.composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
PHP   7. Pimple->offsetGet() /root/.composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:37
PHP   8. Silex\Application::{closure:/root/.composer/vendor/pimple/pimple/lib/Pimple.php:122-130}() /root/.composer/vendor/pimple/pimple/lib/Pimple.php:83
PHP   9. Lstr\DnsmasqMgmt\Service\DnsmasqMgmtServiceProvider->Lstr\DnsmasqMgmt\Service\{closure}() /root/.composer/vendor/pimple/pimple/lib/Pimple.php:126

**Comment by lightster** [comment]
Hi @gpetrache-at-ca,

The exception that is trying to be thrown is an exception that the environment you are trying to use dnsmasq-mgmt in is not supported. The dnsmasq-mgmt tool does not support Ubuntu. Issue #9 is an enhancement request to support Ubuntu if you want to follow that ussue.

I have fixed the "missing" exception so a more informative error will be thrown if you update dnsmasq-mgmt.

Thanks,

Lightster
